version: '2.3'

services:

  mqttbroker:
    image: eclipse-mosquitto
    hostname: mqttbroker
    expose:
      - "1883"
      - "9001"
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - default

  smart-football-table-detection: 
    runtime: nvidia
    build:
      context: smart-football-table-detection
    environment:
      - MQTTHOST=mqttbroker
      - MQTTPORT=1883
    depends_on:
      - "mqttbroker"

  smart-football-table-cognition: 
    image: smart-football-table/cognition
    environment:
      - MQTTHOST=mqttbroker
      - MQTTPORT=1883
    depends_on:
      - "mqttbroker"

  smart-football-table-ui:
    build:
      context: smart-football-table-ui
    volumes:
      - '.:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - '80:80'
    depends_on:
      - "mqttbroker"

  smart-football-table-ledcontrol:
    image: smart-football-table/ledcontrol
    environment:
      - MQTTHOST=mqttbroker
      - MQTTPORT=1883
      - LEDS=72
      - TTY=/dev/ttyUSB0
    devices:
      - "${LED_STRIPE_DEVICE}:/dev/ttyUSB0"
    depends_on:
      - "mqttbroker"

  smart-football-table-sound:
    build:
      context: smart-football-table-sound
    environment:
      - MQTTHOST=mqttbroker
      - MQTTPORT=1883
      - PULSE_SERVER=unix:${XDG_RUNTIME_DIR}/pulse/native
    volumes:
      - '${XDG_RUNTIME_DIR}/pulse/native:${XDG_RUNTIME_DIR}/pulse/native'
      - '~/.config/pulse/cookie:/root/.config/pulse/cookie'
    devices:
      - "/dev/snd"
    depends_on:
      - "mqttbroker"

