version: '2.0'

services:

  mqttbroker: 
    image: eclipse-mosquitto
    expose:
      - "1883"
      - "9001"
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - default

  smart-football-table-ui:
    build:
      context: smart-football-table-ui
      dockerfile: Dockerfile
    volumes:
      - '.:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - '80:80'

  smart-football-table-ledcontrol:
    image: smart-football-table/ledcontrol
    environment:
      - LEDS=72
      - TTY=/dev/ttyUSB0
      - MQTTHOST=mqttbroker
      - MQTTPORT=1883
    devices:
      - "/dev/serial/by-id/usb-1a86_USB2.0-Serial-if00-port0:/dev/ttyUSB0"

  smart-football-table-sound:
    build:
      context: smart-football-table-sound
      dockerfile: Dockerfile
    environment:
      - MQTTHOST=mqttbroker
      - MQTTPORT=1883

